export const meta = {
    'angular-directive-takeuntil': {
        title: 'Directive Composition API in Angular 15',
        description: 'A resuable pattern unsubscribing observables using takeUntil operator.',
        coverImage: '/posts/directive-composition.png',
        tags: 'Angular',
        date: '2022-10-24T12:30:07.322Z',
        updateDate: '2022-10-24T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/angular-directive-takeuntil'
    },
    'create-blog-from-scratch': {
        title: 'Why Developers Should Create Their Own Blog From Scratch',
        description: 'Creating your own blog can be time consuming but also a great learning experience.',
        coverImage: '/posts/blog-platform.jpeg',
        tags: 'Web',
        date: '2022-10-14T12:30:07.322Z',
        updateDate: '2022-10-14T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/create-blog-from-scratch'
    },
    'podcast-pwa': {
        title: 'Develop Podcast PWA App?',
        description: 'How cool would it be to open source a podcast app. Any designers or developers?',
        coverImage: '/posts/podcast-blog.jpeg',
        tags: 'PWA',
        date: '2022-10-15T12:30:07.322Z',
        updateDate: '2022-12-28T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/podcast-pwa',
    },
    'current-state-of-pwa': {
        title: 'Current State of Progressive Web Apps',
        description: 'How progressive web apps are growing in the community',
        coverImage: '/posts/pwa-logo.jpeg',
        tags: 'PWA',
        date: '2022-10-10T12:30:07.322Z',
        updateDate: '2022-10-10T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/current-state-of-pwa',
    },
    'fitvitfitness-portfolio': {
        title: 'Featured Project - FitVitFitness.com',
        description: 'A fitness blog about weight training and tips for a healthy life style.',
        coverImage: '/posts/fitvit/fitvit.jpeg',
        tags: 'Projects',
        date: '2023-01-04T12:30:07.322Z',
        updateDate: '2023-01-04T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/fitvitfitness-portfolio'
    },
    'open-graph-meta-tags': {
        title: "How to Set Up Open Graph Meta Tags",
        description: "Easy way of understanding how and what is Open Graph for social media sites.",
        coverImage: "/posts/open-graph/images.jpeg",
        tags: "Web",
        date: "2022-11-05T12:30:07.322Z",
        updateDate: "2023-01-06T12:30:07.322Z",
        author: 'Jerry Gagliano',
        picture: '',
        path: "/posts/open-graph-meta-tags",
    },
    'why-developers-need-to-blog': {
        title: '4 Reasons Why Developers or Designers Should Have a Blog',
        description: 'Blogging can be time consuming but will help you in the long run.',
        coverImage: '/posts/blog.jpeg',
        tags: 'Web',
        date: '2022-10-01T12:30:07.322Z',
        updateDate: '2022-10-01T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/why-developers-need-to-blog',
    },
    'microservices-architecture-over-monolithic': {
        title: 'Choosing Mircoservice over Monolithic Architecture',
        description: 'How I architected a site with a microservice with Node.js and communicating with MailChimp',
        coverImage: '/posts/blog-microservice-min.jpg',
        tags: 'Web',
        date: '2023-01-23T12:30:07.322Z',
        updateDate: '2023-01-23T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/microservices-architecture-over-monolithic',
    }
}