export const meta = {
    'angular-directive-takeuntil': {
        title: 'Directive Composition API in Angular 15',
        description: 'With angular\'s new release version 15 we look into a resuable pattern unsubscribing observables using takeUntil operator.',
        coverImage: '/posts/directive-composition.png',
        tags: 'Angular',
        date: '2022-10-24T12:30:07.322Z',
        updateDate: '2022-10-24T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/angular-directive-takeuntil/'
    },
    'create-blog-from-scratch': {
        title: 'Why Developers Should Create Their Own Blog From Scratch',
        description: 'Creating your own blog from scratch can be time consuming but also a great technical learning experience. As your in full control of your platform.',
        coverImage: '/posts/blog-platform.jpeg',
        tags: 'Web',
        date: '2022-10-14T12:30:07.322Z',
        updateDate: '2022-10-14T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/create-blog-from-scratch/'
    },
    'podcast-pwa': {
        title: 'Open Sourcing A Podcast PWA App',
        description: 'Highly interested in open sourcing a podcast app using progressive web app technologies.',
        coverImage: '/posts/podcast-blog.jpeg',
        tags: 'PWA',
        date: '2022-10-15T12:30:07.322Z',
        updateDate: '2022-12-28T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/podcast-pwa/',
    },
    'current-state-of-pwa': {
        title: 'Current State of Progressive Web Apps',
        description: 'As the web is evolving and more in demand as progressive web app development is growing, allowing developers creating mobile native app user experiences.',
        coverImage: '/posts/pwa-logo.jpeg',
        tags: 'PWA',
        date: '2022-10-10T12:30:07.322Z',
        updateDate: '2022-10-10T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/current-state-of-pwa/',
    },
    'fitvitfitness-portfolio': {
        title: 'My Side FitVitFitness.com',
        description: 'Side project about a personal certified trainer. Providing workout programs and writing blogs. Motivating people to have healthy life style.',
        coverImage: '/posts/fitvit/fitvit.jpeg',
        tags: 'Projects',
        date: '2023-01-04T12:30:07.322Z',
        updateDate: '2023-01-04T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/fitvitfitness-portfolio/'
    },
    'open-graph-meta-tags': {
        title: "How to Set Up Open Graph Meta Tags",
        description: "Easy way of understanding how and what is Open Graph for social media. Improving your site links how they look and feel when shared through social media.",
        coverImage: "/posts/open-graph/images.jpeg",
        tags: "Web",
        date: "2022-11-05T12:30:07.322Z",
        updateDate: "2023-01-06T12:30:07.322Z",
        author: 'Jerry Gagliano',
        picture: '',
        path: "/posts/open-graph-meta-tags",
    },
    'why-developers-need-to-blog': {
        title: 'Why Developers Should Have a Blog',
        description: 'Reasons why developers or designers should blog. Why it\'s important as it builds up their brand and share their experiences.',
        coverImage: '/posts/blog.jpeg',
        tags: 'Web',
        date: '2022-10-01T12:30:07.322Z',
        updateDate: '2023-01-23T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/why-developers-need-to-blog/',
    },
    'microservices-architecture-over-monolithic': {
        title: 'Choosing Mircoservice over Monolithic Architecture',
        description: 'How I architect my site with a microservice Node.js environment. How microservices could benefit over monolithic architecture.',
        coverImage: '/posts/blog-microservice-min.jpg',
        tags: 'Web',
        date: '2023-01-23T12:30:07.322Z',
        updateDate: '2023-01-23T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/microservices-architecture-over-monolithic/',
    },
    'reactjs-vs-web-components': {
        title: 'Choosing Web Components Over ReactJS',
        description: 'Web components standards has caught up and this article will discuss why developers should begin using them over ReactJS.',
        coverImage: '/posts/web-reactjs.jpeg',
        tags: 'Web',
        date: '2023-02-06T12:30:07.322Z',
        updateDate: '2023-02-06T12:30:07.322Z',
        author: 'Jerry Gagliano',
        picture: '',
        path: '/posts/reactjs-vs-web-components/',
    }
}